name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 5.0.3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  quiver: ^3.2.1
  path: ^1.9.0
  xml: ^6.4.2
  image: ^4.1.7
  collection: ^1.18.0

dev_dependencies:
  test: ^1.25.7
  flutter_lints: ^4.0.0
